services:
  postgis:
    image: postgis/postgis:17.3.5
    container_name: postgis_simulacion
    restart: always
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=gis
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgis:/var/lib/postgresql/data
      - ./bd.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - postgis_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_postgis
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "9090:80"
    networks:
      - postgis_net
    depends_on:
      - postgis

networks:
  postgis_net:
    driver: bridge