services:
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_ecommerce
    restart: always
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecommerce_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ecommerce
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    networks:
      - ecommerce_network
    depends_on:
      - postgres_db

volumes:
  postgres_data:

networks:
  ecommerce_network:
    driver: bridge
