name: FastAPI CI

on:
  push:
    branches:
      - main
      - backend
      - integracion
  pull_request:
    branches:
      - main
      - backend
      - integracion

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgis:
        image: postgis/postgis:17-3.5
        env:
          POSTGRES_DB: gis
          POSTGRES_USER: gis
          POSTGRES_PASSWORD: password
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: "backend/pyproject.toml"

      - name: Instalar Python
        run: uv python install

      - name: Ejecutar pruebas
        working-directory: ./backend
        env:
          DATABASE_URL: postgresql://gis:password@localhost:5433/gis
          SECRET_KEY: "Bon Voyage"
          ALGORITHM: "HS256"
        run: uv run pytest -v

